#!/bin/sh

alias a="$EDITOR ~/.config/aliases"

# GIT
alias gs="git status"
alias ga="git add"
alias gc="git commit"

# CPU profile
alias cpu-max='tuned-adm profile latency-performance'
alias cpu-balanced='tuned-adm profile balanced'
alias cpu-min='tuned-adm profile laptop-battery-powersave'

# Some commands that are useful but too long to remember
alias ports="ss --listening --tcp --udp --all --numeric"

# Add verbosity to commands
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -vI"

# Add colors
alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ccat="highlight --out-format=ansi"

# Add alternatives for builtins
alias ..="cd .."
alias ...="cd ../.."
alias ls="exa -hl --color=always --group-directories-first"
alias la="ls -a"
alias sudo="doas --"
alias vim="nvim"
alias vi="vim"
alias v="vim"

# Grep
alias rgrep="grep -r"
alias egrep="grep -E"

# Main directories
alias uam="cd $HOME/uam/semestr5"
alias dp="cd $HOME/uam/semestr5/dynamika-procesów-grupowych"
alias dpg="cd $HOME/uam/semestr5/dynamika-procesów-grupowych"
alias gk="cd $HOME/uam/semestr5/grafika-komputerowa"
alias grk="cd $HOME/uam/semestr5/grafika-komputerowa"
alias jf="cd $HOME/uam/semestr5/języki-formalne-i-złożoność-obliczeniowa"
alias ma="cd $HOME/uam/semestr5/muzyka-algorytmiczna"
alias pj="cd $HOME/uam/semestr5/przetwarzanie-języka-naturalnego"
alias pjn="cd $HOME/uam/semestr5/przetwarzanie-języka-naturalnego"

alias dotfiles="cd $HOME/repos/dotfiles"

alias cl="cat ~/terminy | ~/dev/as-cal/as-cal"

alias stacky="cd ~/dev/stacky"

alias bendun.cc="cd ~/dev/bendun.cc/home-2.0"
alias devlog="$EDITOR ~/dev/bendun.cc/home-2.0/src/devlog.md"
